# version: '3.8'
services:
  postgres:
    image: postgres:11.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./schema/schema_postgres.sql:/docker-entrypoint-initdb.d/1.sql
      - ./schema/data.sql:/docker-entrypoint-initdb.d/2.sql
volumes:
  db: